export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_POSTS = "LOAD_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const ADD_POST = "ADD_POST";
export const UPDATE_POST = "UPDATE_POST";

export const LOAD_USER = "LOAD_USER"
export const UPDATE_USER_PROFILE_IMAGE = "UPDATE_USER_PROFILE_IMAGE"
export const CLOSE_WELCOME_MESSAGE = "CLOSE_WELCOME_MESSAGE"


export const LOAD_FRIEND_REQUESTS = "LOAD_FRIEND_REQUESTS"
export const LOAD_FRIEND_REQUESTS_SENT = "LOAD_FRIEND_REQUESTS_SENT"
export const ADD_FRIEND_REQUEST_SENT = "ADD_FRIEND_REQUEST_SENT"
export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST"


export const LOAD_FRIENDS = "LOAD_FRIENDS"
export const ADD_FRIEND = "ADD_FRIEND"
export const REMOVE_FRIEND_REQUEST_SENT = "REMOVE_FRIEND_REQUEST_SENT"
export const REMOVE_USER = "REMOVE_USER"

export const REMOVE_FRIEND = "REMOVE_FRIEND"
