export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_MOVIES = "LOAD_MOVIES";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const ADD_MOVIE = "ADD_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";

export const LOAD_MEALS = "LOAD_MEALS";
export const REMOVE_MEAL = "REMOVE_MEAL";
export const ADD_MEAL = "ADD_MEAL";
export const UPDATE_MEAL = "UPDATE_MEAL"


export const LOAD_TVSHOWS = "LOAD_TVSHOWS";
export const REMOVE_TVSHOW = "REMOVE_TVSHOW";
export const ADD_TVSHOW = "ADD_TVSHOW"
export const UPDATE_TVSHOW = "UPDATE_TVSHOW"

export const LOAD_USER = "LOAD_USER"
export const UPDATE_USER_PROFILE_IMAGE = "UPDATE_USER_PROFILE_IMAGE"
export const LOAD_FRIEND_REQUESTS = "LOAD_FRIEND_REQUESTS"
export const LOAD_FRIENDS = "LOAD_FRIENDS"
export const ADD_PERSONAL_RECOMMENDATION = "ADD_PERSONAL_RECOMMENDATION"
export const LOAD_PERSONAL_RECOMMENDATIONS = "LOAD_PERSONAL_RECOMMENDATIONS"
export const REMOVE_PERSONAL_RECOMMENDATION = "REMOVE_PERSONAL_RECOMMENDATION"
